# Generated by Django 6.0.1 on 2026-02-02 15:12

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name="HaystackIndex_Core_Anothermockmodel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("django_id", models.CharField(max_length=255)),
                ("django_ct", models.CharField(max_length=255)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                ("text", models.TextField(null=True)),
                ("pub_date", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "haystack_index_core_anothermockmodel",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"],
                        name="haystack_index_core_anothermockmodel_sv_gin",
                    )
                ],
                "unique_together": {("django_ct", "django_id")},
            },
        ),
        migrations.CreateModel(
            name="HaystackIndex_Core_Mockmodel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("django_id", models.CharField(max_length=255)),
                ("django_ct", models.CharField(max_length=255)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                ("text", models.TextField(null=True)),
                ("author", models.TextField(null=True)),
                ("pub_date", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "haystack_index_core_mockmodel",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"],
                        name="haystack_index_core_mockmodel_sv_gin",
                    )
                ],
                "unique_together": {("django_ct", "django_id")},
            },
        ),
        migrations.CreateModel(
            name="HaystackIndex_Core_Scoremockmodel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("django_id", models.CharField(max_length=255)),
                ("django_ct", models.CharField(max_length=255)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                ("text", models.TextField(null=True)),
                ("score", models.TextField(null=True)),
            ],
            options={
                "db_table": "haystack_index_core_scoremockmodel",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"],
                        name="haystack_index_core_scoremockmodel_sv_gin",
                    )
                ],
                "unique_together": {("django_ct", "django_id")},
            },
        ),
    ]
