# Generated by Django 6.0.1 on 2026-02-04 14:48

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.operations
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.CreateModel(
            name="HaystackIndex_Core_Allfieldsmodel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("django_id", models.CharField(max_length=255)),
                ("django_ct", models.CharField(max_length=255)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                ("text", models.TextField(null=True)),
                ("name_ngram", models.TextField(null=True)),
                ("is_active", models.BooleanField(null=True)),
                ("count", models.IntegerField(null=True)),
                ("rating", models.FloatField(null=True)),
                ("price", models.TextField(null=True)),
                ("created_date", models.DateField(null=True)),
                ("created_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "haystack_index_core_allfieldsmodel",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"],
                        name="haystack_index_core_allfieldsmodel_sv_gin",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.indexes.OpClass(
                            models.F("name_ngram"), name="gin_trgm_ops"
                        ),
                        name="haystack_index_core_allfieldsmodel_name_ngram_trgm",
                    ),
                ],
                "unique_together": {("django_ct", "django_id")},
            },
        ),
        migrations.CreateModel(
            name="HaystackIndex_Core_Anothermockmodel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("django_id", models.CharField(max_length=255)),
                ("django_ct", models.CharField(max_length=255)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                ("text", models.TextField(null=True)),
                ("pub_date", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "haystack_index_core_anothermockmodel",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"],
                        name="haystack_index_core_anothermockmodel_sv_gin",
                    )
                ],
                "unique_together": {("django_ct", "django_id")},
            },
        ),
        migrations.CreateModel(
            name="HaystackIndex_Core_Mockmodel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("django_id", models.CharField(max_length=255)),
                ("django_ct", models.CharField(max_length=255)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                ("text", models.TextField(null=True)),
                ("author", models.TextField(null=True)),
                ("pub_date", models.DateTimeField(null=True)),
                (
                    "categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list, null=True
                    ),
                ),
            ],
            options={
                "db_table": "haystack_index_core_mockmodel",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"],
                        name="haystack_index_core_mockmodel_sv_gin",
                    )
                ],
                "unique_together": {("django_ct", "django_id")},
            },
        ),
        migrations.CreateModel(
            name="HaystackIndex_Core_Scoremockmodel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("django_id", models.CharField(max_length=255)),
                ("django_ct", models.CharField(max_length=255)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                ("text", models.TextField(null=True)),
                ("score", models.TextField(null=True)),
            ],
            options={
                "db_table": "haystack_index_core_scoremockmodel",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"],
                        name="haystack_index_core_scoremockmodel_sv_gin",
                    )
                ],
                "unique_together": {("django_ct", "django_id")},
            },
        ),
    ]
